apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'

def feedbackEmail
def isRSTPublicRelease = System.env.RST_PUBLIC_RELEASE
if (isRSTPublicRelease) {
    println("Performing signed release build")
    apply from: "loadPrivateData.gradle"
    println("Got props:" + privateProps)
    feedbackEmail = privateProps['rst.feedbackEmail']
    if (feedbackEmail == null || feedbackEmail.isEmpty()) {
        throw new GradleException("No feedback e-mail set")
    }
} else {
    println("Performing regular build")
    feedbackEmail = "feedback@test.com"
}
def versionProps = new Properties()
file("../version.properties").withInputStream {
    stream -> versionProps.load(stream)
}
def releaseVersion = "${versionProps['rst.major_version']}" +
        ".${versionProps['rst.minor_version']}" +
        ".${versionProps['rst.version_code']}"
archivesBaseName = "open-sms-locator-$releaseVersion"

android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "ru.rst.rescuesmstracker"
        namespace "ru.rst.rescuesmstracker"
        minSdkVersion 26
        targetSdkVersion 36
        versionCode String.format("%d%03d%04d",
                versionProps['rst.major_version'] as Integer,
                versionProps['rst.minor_version'] as Integer,
                versionProps['rst.version_code'] as Integer) as Integer
        versionName releaseVersion

        buildConfigField "String", "FEEDBACK_EMAIL", "\"$feedbackEmail\""
    }
    if (isRSTPublicRelease) {
        signingConfigs {
            config {
                keyAlias privateProps['rst.keyAlias']
                keyPassword privateProps['rst.keyPassword']
                storeFile keyStoreFile
                storePassword privateProps['rst.storePassword']
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (isRSTPublicRelease) {
                signingConfig signingConfigs.config
            }
        }
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    buildFeatures {
        buildConfig true
        viewBinding true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "androidx.core:core-ktx:1.13.1"
    implementation "io.reactivex.rxjava2:rxjava:2.2.21"
    implementation "io.reactivex.rxjava2:rxandroid:2.1.1"
}

task incrementVersion {
    doLast {
        versionProps['rst.version_code'] = ((versionProps['rst.version_code'] as Integer) + 1).toString()
        file("../version.properties").withOutputStream {
            stream -> versionProps.store(stream, "version autoincrement")
        }
    }
}

task pushVersion {
    doLast {
        println("Commiting version")
        new ProcessBuilder("git", "commit", "-m", "[skip ci] Version autoincrement", "version.properties").start().waitFor()
        println("Creating tag")
        new ProcessBuilder("git", "tag", "-a", releaseVersion, "-m", "Release published").start().waitFor()
        println("Pushing tag")
        "git push --all --follow-tags".execute().waitFor()
    }
}
