apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

def isPublicRelease = System.env.LLEGUE_PUBLIC_RELEASE
if (isPublicRelease) {
    println("Performing signed release build")
    apply from: "loadPrivateData.gradle"
} else {
    println("Performing regular build")
}
def versionProps = new Properties()
file("../version.properties").withInputStream {
    stream -> versionProps.load(stream)
}
def releaseVersion = "${versionProps['llegue.major_version']}" +
        ".${versionProps['llegue.minor_version']}" +
        ".${versionProps['llegue.version_code']}"
archivesBaseName = "llegue-$releaseVersion"

android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "app.llegue"
        namespace "app.llegue"
        minSdkVersion 26
        targetSdkVersion 36
        versionCode String.format("%d%03d%04d",
                versionProps['llegue.major_version'] as Integer,
                versionProps['llegue.minor_version'] as Integer,
                versionProps['llegue.version_code'] as Integer) as Integer
        versionName releaseVersion
    }
    if (isPublicRelease) {
        signingConfigs {
            config {
                keyAlias privateProps['llegue.keyAlias']
                keyPassword privateProps['llegue.keyPassword']
                storeFile keyStoreFile
                storePassword privateProps['llegue.storePassword']
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (isPublicRelease) {
                signingConfig signingConfigs.config
            }
        }
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    buildFeatures {
        buildConfig true
        viewBinding true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "androidx.core:core-ktx:1.13.1"

    implementation "androidx.room:room-runtime:2.8.4"
    implementation "androidx.room:room-ktx:2.8.4"
    kapt "androidx.room:room-compiler:2.8.4"
}

task incrementVersion {
    doLast {
        versionProps['llegue.version_code'] = ((versionProps['llegue.version_code'] as Integer) + 1).toString()
        file("../version.properties").withOutputStream {
            stream -> versionProps.store(stream, "version autoincrement")
        }
    }
}
